# **What is data?**
***Collection of raw facts, figures or observations are called data.***

# **Types of data**
✔***Structured***

✔***Unstructured***

✔***Semistructured***

# **Structured**
***Well organized data in the form of rows and columns is known as structured data***
# **Unstructured**
***Data available in the form of text , audio , video and images is known as unstructured data***
# **Semi-structured**
***Data in the format of JSON , XML files is calles semi-structured data***

# **Importance of data in ML**
✔***Acts as fuil for ML algorithms***

✔***Directly impacts Model's accuracy and reliability***

✔***Without quality data , even advanced models fail***

# **Key characteristics of high quality data**
✔***Data should be relevent***

✔***Data should be reliable and error free***

✔***covers different cases and variations, Data should have diversity***

✔***There should be enough quantity of data for training models***


# **Role of data in ML pipeline:**
✔***Collection: Gathering data***

✔***Pre-processing: Cleaning and transforming***

✔***Feature engineering: extracting usefull features***

✔***Model training: feeding data into algorithems***

✔***Evaluation: testing model performance***

# **What is NumPy?**
***It is a Python library used for working with numbers, arrays, matrices, and mathematical operations efficiently.***
# **Key Features:**
✔***provide N-dimentional arrays***

✔***Fast Computation***

✔***Mathematical Functions***

✔***Array Operations***

✔***Linear Algebra***

✔***Statistical Functions***

✔***Memory Efficient***

In [1]:
!pip install numpy

In [2]:
import numpy as np
import time
np_arr=np.array([[2,4,6],[1,3,5]])

In [3]:
print(np_arr)
print(np_arr.ndim)
print(np_arr.dtype)
print(np_arr.shape)

[[2 4 6]
 [1 3 5]]
2
int64
(2, 3)


In [4]:
python_list=list(range(1000000))
python_res=[]
start_time=time.time()
for i in python_list:
    python_res.append(i+5)
end_time=time.time()
print("time taken by python list: ",end_time-start_time)

time taken by python list:  0.3430206775665283


In [5]:
np_arr=np.arange(1000000)
start_time=time.time()
np_res=np_arr+5
end_time=time.time()
print("np arr time: ",end_time-start_time)


np arr time:  0.004744052886962891


In [6]:
arr1=np.array([2,3,4,5,6])
print(arr1)

[2 3 4 5 6]


In [7]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [9]:
print(np.full((3,4),6))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [10]:
print(np.arange(3,10,2))

[3 5 7 9]


In [11]:
print(np.linspace(1,2,3))

[1.  1.5 2. ]


In [12]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [14]:
print(np.diag((1,2,3)))


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
arr2=np.array([2.11,3.55,6.77])
print(arr2.astype(int))

[2 3 6]


# **NumPy Indexing, Slicing and Strides:**

# **Indexing**

In [17]:
arr=np.array([[20,30,40],
              [50,60,70],
              [80,90,100]])
print(arr[0,2])           # 40 (1st row,3rd column)
print(arr[1,1])           # 300 (2nd row, 2nd column)

40
60


In [18]:
print(arr[-1,-2])         # 90 (last row , second last column)
print(arr[-1,-1])         # 100 (last row , last column)

90
100


In [19]:
# Genral form: [ stat , stop , step ]
print(arr[0:2,0:1])

[[20]
 [50]]


In [20]:
dig_matrix=np.identity(5)
print(dig_matrix[::2,::2])  # (every 2nd row and 2nd column)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Slicing**

In [21]:
slice_arr=arr[0,:2]
print(slice_arr)

[20 30]


In [22]:
slice_arr[0]=10    # its view not copy so change original array.
print(arr[0][0])

10


In [23]:
copy_arr=arr[0].copy  # copy of array
copy_arr=5
print(copy_arr)

5


In [24]:
print(arr[0][0])      # unchanged original

10


# **Strides**
***Stride tells NumPy how far it needs to jump in memory to reach the next element along each dimension.***

In [25]:
one_dim_arr=np.array([12,13,14,15,16])
print(one_dim_arr.strides)

(8,)


In [26]:
two_dim_arr=np.array([[3,6,9,12,15],
                      [4,8,12,16,20],
                      [5,10,15,20,25]])
print(two_dim_arr.strides)                # (40,8) move 40 bytes in each row because every row contaions 5 elements (8*5) and 8 bytes in each column.

(40, 8)


# **Random Number Genration:**

In [27]:
rng=np.random.default_rng(seed=10)       # with seed it produces same sequince every time (usefull for ML).
flips=rng.integers(0,2,size=100000)
prob_heads=np.mean(flips)
print(prob_heads)

0.49862


# **Practice:**

In [28]:
# sum of two matrices:
ones_matrix=np.ones((3,3))
diag_matrix=np.diag((1,2,3))


In [29]:
print(ones_matrix+diag_matrix)

[[2. 1. 1.]
 [1. 3. 1.]
 [1. 1. 4.]]


In [30]:
# product of two matrices:
print(ones_matrix*diag_matrix)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [31]:
# row and column operatons:
prime_num_matrix=np.array([[1,2,3],
                           [5,7,11],
                           [13,17,19]])
print(prime_num_matrix.sum(axis=0))

[19 26 33]


In [32]:
# Transpose of numpy arr:
trans_arr=prime_num_matrix.T
print(trans_arr)

[[ 1  5 13]
 [ 2  7 17]
 [ 3 11 19]]


In [33]:
# Total bytes contained by arr:
print(arr.nbytes)

72


In [34]:
# Max value index:
print(arr)
print(arr.argmax())

[[ 10  30  40]
 [ 50  60  70]
 [ 80  90 100]]
8


In [35]:
# Min value index:
print(arr.argmin())

0


In [36]:
# Sorted values index:
print(arr.argsort())

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [37]:
# changing data type of arr:
arr=np.array([1.2,2.8,3.9,5.4])
print(arr)
print(arr.dtype)
print(type(arr))
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)


[1.2 2.8 3.9 5.4]
float64
<class 'numpy.ndarray'>
[1 2 3 5]
int64


In [38]:
# add a num with arr
int_arr=int_arr+3          
print(int_arr)

[4 5 6 8]


In [39]:
# take sqaure of each element of arr
int_arr=int_arr**2         
print(int_arr)


[16 25 36 64]


In [40]:
# perform statistical operations on arr:
print(np.sum(int_arr))
print(np.max(int_arr))
print(np.min(int_arr))
print(np.mean(int_arr))
print(np.std(int_arr))
print(np.var(int_arr))


141
64
16
35.25
18.046814123273947
325.6875


In [41]:
# accessing element at specefic index of arr:
print(int_arr[3])
arr=[[2,3,4,5],[6,7,8,9]]
arr_2D=np.array(arr)
print(arr_2D[0][2])


64
4


In [42]:
# accessing specific part of arr using slicing:
_arr=[2,3,4,5,6,7]
print(_arr[1:6:2]) 

[3, 5, 7]


In [43]:
# reverse arr using negative slicing 
rev_arr=_arr[::-1]      
print(rev_arr)

[7, 6, 5, 4, 3, 2]


In [44]:
# fancy indexing
_arr=np.array(_arr)
print(_arr[[0,2,4]])    


[2 4 6]


In [45]:
# Boolean masking faster than loops
print(_arr[_arr>4]) 


[5 6 7]


In [46]:
# reshape arr from 1D to 2D without changing arr data    
_arr=_arr.reshape(3,2)  
print(_arr)


[[2 3]
 [4 5]
 [6 7]]


In [47]:
# change multi dim arr into 1D arr by returning it's view
_arr_1D=_arr.ravel()    
_arr_1D[0]=10           # changing value at 0th index
print(_arr_1D)
print(_arr)             # change reflect at orginal arr due to ravel()

[10  3  4  5  6  7]
[[10  3]
 [ 4  5]
 [ 6  7]]


In [48]:
# change multi dim arr into 1D arr by returning it's copy
ar1=[[10,20,30,40],[15,25,35,45]]
ar1=np.array(ar1)
_ar1=ar1.flatten()      
_ar1[0]=5               # changing value at 0th index
print(_ar1)
print(ar1)              # change does not reflect at orginal arr due to flatten()


[ 5 20 30 40 15 25 35 45]
[[10 20 30 40]
 [15 25 35 45]]


In [49]:
# insert value
print(_arr_1D)
new_arr=np.insert(_arr_1D,1,9)    # insert(array,indx,value)
print(new_arr)
print(ar1)
new_ar1=np.insert(ar1,1,[100,200,300,400],axis=0)
print(new_ar1)

[10  3  4  5  6  7]
[10  9  3  4  5  6  7]
[[10 20 30 40]
 [15 25 35 45]]
[[ 10  20  30  40]
 [100 200 300 400]
 [ 15  25  35  45]]


In [50]:
# append value in arr:
updated_arr=np.append(_arr_1D,[9,10])    
print(_arr_1D)
print(updated_arr)

[10  3  4  5  6  7]
[10  3  4  5  6  7  9 10]


In [51]:
# concatenation (union) of arr:
ar1=np.array([2,4,6,8])
ar2=np.array([10,12,14,16])
ar_sum=np.concatenate((ar1,ar2),axis=0)
print(ar_sum)


[ 2  4  6  8 10 12 14 16]


In [52]:
# deletion of arr:
new_ar_sum=np.delete(ar_sum,-1)
print("before deletion: ")
print(ar_sum)
print("after deletion:")
print(new_ar_sum)
_arr_2D=np.delete(arr_2D,0,axis=0)
print("before deletion:")
print(arr_2D)
print("after deletion:")
print(_arr_2D)

before deletion: 
[ 2  4  6  8 10 12 14 16]
after deletion:
[ 2  4  6  8 10 12 14]
before deletion:
[[2 3 4 5]
 [6 7 8 9]]
after deletion:
[[6 7 8 9]]


In [53]:
# vertically stack:
print(ar1)
print(ar2)
new_ar=np.vstack((ar1,ar2))
print(new_ar)


[2 4 6 8]
[10 12 14 16]
[[ 2  4  6  8]
 [10 12 14 16]]


In [54]:
# horizontally stack:
print(ar1)
print(ar2)
new_ar=np.hstack((ar1,ar2))
print(new_ar)


[2 4 6 8]
[10 12 14 16]
[ 2  4  6  8 10 12 14 16]


In [55]:
# split an arr:
new_ar1=np.split(ar1,2)
print(new_ar1)


[array([2, 4]), array([6, 8])]


In [56]:
# broadcasting:
prices=np.array([100,200,300,400])
discount=10/100
final_prices=prices-prices*discount
print(final_prices)


[ 90. 180. 270. 360.]


In [57]:
# vectorization:
ar3=np.array([10,20,30])
ar4=np.array([100,200,300])
res=ar3+ar4
multiplied=ar4*2
print(res)
print(multiplied)


[110 220 330]
[200 400 600]


In [58]:
# missing values:
_arr2=np.array([1,np.nan,2,3,4,np.nan])
print(np.isnan(_arr2))    # return true at the places where missing value occur.

[False  True False False False  True]


In [59]:
# replace missing values with 100.
cleaned_arr2=np.nan_to_num(_arr2,nan=100)   
print(cleaned_arr2)

[  1. 100.   2.   3.   4. 100.]


In [60]:
# infinite values:
_arr2=np.append(_arr2,np.inf)
print(np.isinf(_arr2))
print(_arr2)

[False False False False False False  True]
[ 1. nan  2.  3.  4. nan inf]


In [61]:
# replace infinite values with finite number:
cleaned_arr2=np.nan_to_num(_arr2,posinf=1000)
print(cleaned_arr2)


[   1.    0.    2.    3.    4.    0. 1000.]
